"""Initial migration

Revision ID: b484a7743810
Revises: 
Create Date: 2024-07-11 12:13:55.989229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b484a7743810'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('full_workflow_configuration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuda_device', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('model', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('kit_name', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('full_workflow_configuration', schema=None) as batch_op:
        batch_op.drop_column('kit_name')
        batch_op.drop_column('model')
        batch_op.drop_column('cuda_device')

    # ### end Alembic commands ###
